### PR TITLE
allow bring your own div with useClickAwayListener

### PR DESCRIPTION
**Pull request by Alphy11**
Click away listener is great, but it adds extra layers of divs inside which can mess with styling.  So I migrated the logic into a hook, so people can bring their own div.

While I was updating, I noticed a bug where the handler was being hooked up on every render because there was no dependencies passed in, so I added dependencies to decrease handler updates.

I also noticed lint was not working, so I updated the rules to work.  Let me know if you'd rather me just remove linting, rather than updating.

@ooade

### CODE REVIEW

**Comment by ooade** [comment]
I don't think there are a lot of updates to be done. For the styling issue, we could spread props from the parent component to the div; That way they can style the Listener Component appropriately. 

I missed the eslint rules. We can have that. I probably need to setup prettier so that we can have exact diffs next time, my bad. 

For the dependency array, I don't think it matters much because of the event listeners; they'll always remain alive. But, if I'm missing something please bring it to my attention. Thanks!

**Comment by Alphy11** [comment]
@ooade Sorry, I am not sure what you mean by `I don't think there are a lot of updates to be made` Are you saying you don't want my PR that abstracts the functionality into a hook?  OR are you saying I don't need to change much?

For dependency array, right now, every time the component renders it re-hooks into the event listeners, which is unneccessary, we should only do that when our handler changes.  It's a performance issue.  A small one, but it adds up.

**Comment by ooade** [comment]
Let's not abstract it to a hook. It kinda feels a little bit weird as a hook given that the input is a ref and one would need to pass a callback too.

We'd love to have the dependency array update and the eslint rules fix. Thanks 🙏

**Comment by Alphy11** [comment]
Sure, I can clean up the branch to remove that feature 
Just an FYI, I am going to fork this and publish it as a hook rather than this interface, as my team needs more flexibility.  Thanks for sharing this out.  Super helpful!

**Comment by ooade** [comment]
Sure. Feel free to do that :)

**Comment by ooade** [comment]
Kindly merge master to your branch while you're at it. Thanks.

**Comment by Alphy11** [comment]
Since I ahve my own fork wiht my own work, it's a headache to either detach, or make a branch that is more close to your work.  I think the best course of action is to copy paste the config files on your own local branch to grab these changes.  Sorry for the inconvenience here!

**Pull request closed without merging**
